#!/usr/bin/env bats

load test_helper

PUBLISH=""
RULES_DIR=""

setup() {
  setup_sage_env
  PUBLISH="$SCRIPT_DIR/bin/sage-publish-rules"
  init_sage
  RULES_DIR="$TEST_DIR/.claude/rules/sage"
}

teardown() {
  teardown_sage_env
}

# add_entry <knowledge file name> <heading> <confidence> <rule text> [paths]
add_entry() {
  {
    printf '\n### %s\n' "$2"
    printf -- '- **Confidence:** %s (1 observation)\n' "$3"
    printf -- '- **Scope:** project\n'
    if [ -n "${5:-}" ]; then printf -- '- **Paths:** %s\n' "$5"; fi
    printf -- '- **Rule:** %s\n' "$4"
    printf -- '- **Evidence:** sessions abc123\n'
    printf -- '- **Added:** 2026-09-17\n'
    printf -- '- **Last seen:** 2026-09-17\n'
  } >> "$TEST_DIR/.sage/knowledge/$1.md"
}

@test "publishes one file per entry, named by rule ID" {
  add_entry pitfalls "NEVER use md5 for password hashing" low "Use bcrypt."
  add_entry conventions "ALWAYS use the imperative mood" low "Write 'Add login'."
  run "$PUBLISH" "$TEST_DIR"
  [ "$status" -eq 0 ]
  [ -f "$RULES_DIR/pitfall-never-use-md5-for-password-hashing.md" ]
  [ -f "$RULES_DIR/convention-always-use-the-imperative-mood.md" ]
  [ "$(ls "$RULES_DIR" | wc -l | tr -d ' ')" -eq 2 ]
}

@test "rule file has the heading and the rule text, and no metadata" {
  add_entry pitfalls "NEVER use md5" medium "Use bcrypt for passwords."
  "$PUBLISH" "$TEST_DIR"
  FILE="$RULES_DIR/pitfall-never-use-md5.md"
  grep -q '^# NEVER use md5$' "$FILE"
  grep -q '^Use bcrypt for passwords\.$' "$FILE"
  refute_grep 'Confidence' "$FILE"
  refute_grep 'Evidence' "$FILE"
  refute_grep 'abc123' "$FILE"
  refute_grep 'Last seen' "$FILE"
}

@test "Paths field becomes paths frontmatter" {
  add_entry pitfalls "NEVER use md5" low "Use bcrypt." 'src/auth/**, `src/**/*.{ts,tsx}`'
  "$PUBLISH" "$TEST_DIR"
  FILE="$RULES_DIR/pitfall-never-use-md5.md"
  [ "$(head -1 "$FILE")" = "---" ]
  grep -q '^  - "src/auth/\*\*"$' "$FILE"
  grep -q '^  - "src/\*\*/\*\.{ts,tsx}"$' "$FILE"
}

@test "entry with no Paths field has no frontmatter" {
  add_entry conventions "ALWAYS use the imperative mood" low "Write 'Add login'."
  "$PUBLISH" "$TEST_DIR"
  FILE="$RULES_DIR/convention-always-use-the-imperative-mood.md"
  [[ "$(head -1 "$FILE")" == "<!-- Generated by sage-code"* ]]
  refute_grep '^paths:' "$FILE"
}

@test "Rule value that continues on an indented line is joined" {
  cat >> "$TEST_DIR/.sage/knowledge/pitfalls.md" <<'MD'

### NEVER use md5
- **Confidence:** low (1 observation)
- **Rule:** Use bcrypt for passwords.
  md5 is not safe.
- **Evidence:** sessions abc123
MD
  "$PUBLISH" "$TEST_DIR"
  grep -q '^Use bcrypt for passwords\. md5 is not safe\.$' "$RULES_DIR/pitfall-never-use-md5.md"
}

@test "publish_min_confidence filters entries" {
  add_entry pitfalls "Low rule" low "Low."
  add_entry pitfalls "Medium rule" medium "Medium."
  add_entry pitfalls "High rule" high "High."
  python3 - "$TEST_DIR/.sage/meta/config.json" <<'PY'
import json, sys
cfg = json.load(open(sys.argv[1]))
cfg["publish_min_confidence"] = "medium"
json.dump(cfg, open(sys.argv[1], "w"), indent=2)
PY
  "$PUBLISH" "$TEST_DIR"
  [ ! -f "$RULES_DIR/pitfall-low-rule.md" ]
  [ -f "$RULES_DIR/pitfall-medium-rule.md" ]
  [ -f "$RULES_DIR/pitfall-high-rule.md" ]
}

@test "second entry with the same rule ID gets the suffix -2" {
  add_entry pitfalls "NEVER use md5" low "First."
  add_entry pitfalls "Never use MD5!" low "Second."
  "$PUBLISH" "$TEST_DIR"
  grep -q '^First\.$'  "$RULES_DIR/pitfall-never-use-md5.md"
  grep -q '^Second\.$' "$RULES_DIR/pitfall-never-use-md5-2.md"
}

@test "file of a pruned entry is deleted, files outside sage/ are kept" {
  add_entry pitfalls "NEVER use md5" low "Use bcrypt."
  "$PUBLISH" "$TEST_DIR"
  echo "# team rule" > "$TEST_DIR/.claude/rules/team.md"
  # Prune: put the knowledge file back to its empty state
  printf '# Pitfalls\n' > "$TEST_DIR/.sage/knowledge/pitfalls.md"
  run "$PUBLISH" "$TEST_DIR"
  [[ "$output" == *"1 removed"* ]]
  [ ! -f "$RULES_DIR/pitfall-never-use-md5.md" ]
  [ -f "$TEST_DIR/.claude/rules/team.md" ]
}

@test "absolute and parent patterns are dropped" {
  add_entry pitfalls "NEVER use md5" low "Use bcrypt." "/etc/passwd, ../outside/**, src/auth/**"
  "$PUBLISH" "$TEST_DIR"
  FILE="$RULES_DIR/pitfall-never-use-md5.md"
  grep -q '^  - "src/auth/\*\*"$' "$FILE"
  refute_grep 'passwd' "$FILE"
  refute_grep 'outside' "$FILE"
}

@test "entry with no valid pattern is published with no path scope, with a warning" {
  add_entry pitfalls "NEVER use md5" low "Use bcrypt." "/etc/passwd"
  run "$PUBLISH" "$TEST_DIR"
  [ "$status" -eq 0 ]
  [[ "$output" == *"warning"*"no valid pattern"* ]]
  refute_grep '^paths:' "$RULES_DIR/pitfall-never-use-md5.md"
}

@test "second run with no change writes nothing" {
  add_entry pitfalls "NEVER use md5" low "Use bcrypt."
  "$PUBLISH" "$TEST_DIR"
  FILE="$RULES_DIR/pitfall-never-use-md5.md"
  touch -t 202001010000 "$FILE"
  run "$PUBLISH" "$TEST_DIR"
  [[ "$output" == *"0 written, 1 unchanged"* ]]
  [ "$(date -r "$FILE" +%Y)" = "2020" ]
}

@test "removes the CLAUDE.md managed section when the two markers are there" {
  cat > "$TEST_DIR/CLAUDE.md" <<'MD'
# Project

Keep this.

## Sage Learnings
<!-- Auto-managed by sage-code plugin. Do not edit below this line. -->
- old rule
<!-- End sage-code managed section -->

## After
Keep this too.
MD
  "$PUBLISH" "$TEST_DIR"
  refute_grep 'Sage Learnings' "$TEST_DIR/CLAUDE.md"
  refute_grep 'old rule' "$TEST_DIR/CLAUDE.md"
  grep -q '^Keep this\.$' "$TEST_DIR/CLAUDE.md"
  grep -q '^## After$' "$TEST_DIR/CLAUDE.md"
  grep -q '^Keep this too\.$' "$TEST_DIR/CLAUDE.md"
}

@test "removing the managed section changes no other text in CLAUDE.md" {
  printf '\n# Project\n\n\n\nThree blank lines above stay.\n\n## Sage Learnings\n<!-- Auto-managed by sage-code plugin. Do not edit below this line. -->\n- old rule\n<!-- End sage-code managed section -->\n\n## After\nKeep.\n\n\n' > "$TEST_DIR/CLAUDE.md"
  printf '\n# Project\n\n\n\nThree blank lines above stay.\n\n## After\nKeep.\n\n\n' > "$TEST_DIR/CLAUDE.md.expected"
  "$PUBLISH" "$TEST_DIR"
  cmp "$TEST_DIR/CLAUDE.md" "$TEST_DIR/CLAUDE.md.expected"
}

@test "changes nothing in CLAUDE.md when the end marker is absent" {
  printf '# Project\n\n## Sage Learnings\n<!-- Auto-managed by sage-code plugin. Do not edit below this line. -->\n- old rule\n' > "$TEST_DIR/CLAUDE.md"
  cp "$TEST_DIR/CLAUDE.md" "$TEST_DIR/CLAUDE.md.before"
  "$PUBLISH" "$TEST_DIR"
  cmp "$TEST_DIR/CLAUDE.md" "$TEST_DIR/CLAUDE.md.before"
}

@test "exits silently when .sage/ directory is missing" {
  EMPTY_DIR=$(mktemp -d)
  run "$PUBLISH" "$EMPTY_DIR"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
  [ ! -d "$EMPTY_DIR/.claude" ]
  rm -rf "$EMPTY_DIR"
}

@test "default config template publishes low confidence entries" {
  add_entry pitfalls "Low rule" low "Low."
  "$PUBLISH" "$TEST_DIR"
  [ -f "$RULES_DIR/pitfall-low-rule.md" ]
  run python3 -c "import json; print(json.load(open('$TEST_DIR/.sage/meta/config.json'))['publish_min_confidence'])"
  [ "$output" = "low" ]
}
